# Generated by Django 4.2.11 on 2026-02-27 13:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("organizations", "0002_alter_organization_options_and_more"),
        ("impersonation", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="impersonationsession",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="impersonationsession",
            name="deleted_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="impersonationsession",
            name="id",
            field=models.UUIDField(
                db_index=True,
                default=uuid.uuid4,
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="impersonationsession",
            name="impersonation_token",
            field=models.CharField(db_index=True, max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name="impersonationsession",
            name="impersonator",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="impersonation_sessions_as_actor",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="impersonationsession",
            name="organization",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="organizations.organization",
            ),
        ),
        migrations.AlterField(
            model_name="impersonationsession",
            name="started_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="impersonationsession",
            name="target",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="impersonation_sessions_as_target",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
