# Generated by Django 4.2.11 on 2026-02-27 13:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("two_factor", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="backupcode",
            name="code_hash",
            field=models.CharField(db_index=True, max_length=64),
        ),
        migrations.AlterField(
            model_name="backupcode",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="backupcode",
            name="deleted_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="backupcode",
            name="id",
            field=models.UUIDField(
                db_index=True,
                default=uuid.uuid4,
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="totpdevice",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="totpdevice",
            name="deleted_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="totpdevice",
            name="id",
            field=models.UUIDField(
                db_index=True,
                default=uuid.uuid4,
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="totpdevice",
            name="is_confirmed",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name="totpdevice",
            name="secret",
            field=models.CharField(max_length=32),
        ),
        migrations.AddIndex(
            model_name="backupcode",
            index=models.Index(
                fields=["user", "is_used"], name="backup_code_user_id_07fbaf_idx"
            ),
        ),
    ]
