# Generated by Django 4.2.11 on 2026-03-05 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_user_options_alter_user_global_role_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="two_fa_method",
            field=models.CharField(
                choices=[("totp", "Authenticator App"), ("email", "Email OTP")],
                default="totp",
                max_length=10,
            ),
        ),
    ]
