# Generated by Django 4.2.11 on 2026-02-27 13:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("plans", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="license",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="licensehistory",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="plan",
            options={"ordering": ["price_monthly_usd"]},
        ),
        migrations.RemoveField(
            model_name="license",
            name="override_features",
        ),
        migrations.RemoveField(
            model_name="plan",
            name="features",
        ),
        migrations.AlterField(
            model_name="license",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="license",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_licenses",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="license",
            name="deleted_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="license",
            name="id",
            field=models.UUIDField(
                db_index=True,
                default=uuid.uuid4,
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="license",
            name="is_suspended",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name="license",
            name="notes",
            field=models.TextField(
                blank=True, help_text="Internal notes about this license deal."
            ),
        ),
        migrations.AlterField(
            model_name="license",
            name="plan",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="licenses",
                to="plans.plan",
            ),
        ),
        migrations.AlterField(
            model_name="license",
            name="valid_from",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="license",
            name="valid_until",
            field=models.DateTimeField(
                blank=True, help_text="Null = lifetime license.", null=True
            ),
        ),
        migrations.AlterField(
            model_name="licensehistory",
            name="changed_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="licensehistory",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="licensehistory",
            name="deleted_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="licensehistory",
            name="id",
            field=models.UUIDField(
                db_index=True,
                default=uuid.uuid4,
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="licensehistory",
            name="new_plan",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="plans.plan",
            ),
        ),
        migrations.AlterField(
            model_name="licensehistory",
            name="previous_plan",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="plans.plan",
            ),
        ),
        migrations.AlterField(
            model_name="licensehistory",
            name="snapshot",
            field=models.JSONField(
                default=dict, help_text="Full license state at time of change."
            ),
        ),
        migrations.AlterField(
            model_name="plan",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="plan",
            name="deleted_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="plan",
            name="features_json",
            field=models.JSONField(
                default=list,
                help_text="List of enabled feature flag strings for this plan.",
            ),
        ),
        migrations.AlterField(
            model_name="plan",
            name="id",
            field=models.UUIDField(
                db_index=True,
                default=uuid.uuid4,
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="plan",
            name="name",
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name="plan",
            name="tier",
            field=models.CharField(
                choices=[
                    ("basic", "Basic"),
                    ("pro", "Pro"),
                    ("premium", "Premium"),
                    ("enterprise", "Enterprise"),
                ],
                db_index=True,
                max_length=20,
                unique=True,
            ),
        ),
        migrations.AddIndex(
            model_name="license",
            index=models.Index(
                fields=["organization", "is_active"], name="licenses_organiz_832d27_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="license",
            index=models.Index(
                fields=["valid_until", "is_active"], name="licenses_valid_u_531be8_idx"
            ),
        ),
    ]
