# Generated by Django 4.2.11 on 2026-02-27 13:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("permissions", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="userpermissionoverride",
            options={"verbose_name": "User Permission Override"},
        ),
        migrations.AlterField(
            model_name="userpermissionoverride",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="userpermissionoverride",
            name="deleted_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="userpermissionoverride",
            name="feature",
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="userpermissionoverride",
            name="granted_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="granted_overrides",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="userpermissionoverride",
            name="id",
            field=models.UUIDField(
                db_index=True,
                default=uuid.uuid4,
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="userpermissionoverride",
            name="is_granted",
            field=models.BooleanField(),
        ),
    ]
