# Generated by Django 4.2.11 on 2026-02-27 13:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("user_sessions", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usersession",
            name="browser",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="usersession",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="usersession",
            name="deleted_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="usersession",
            name="device_type",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="usersession",
            name="id",
            field=models.UUIDField(
                db_index=True,
                default=uuid.uuid4,
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="usersession",
            name="jti",
            field=models.CharField(
                db_index=True,
                help_text="JWT ID of the refresh token.",
                max_length=36,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="usersession",
            name="os",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="usersession",
            name="revoked_reason",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddIndex(
            model_name="usersession",
            index=models.Index(
                fields=["user", "is_active"], name="user_sessio_user_id_bb1b83_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="usersession",
            index=models.Index(
                fields=["expires_at", "is_active"],
                name="user_sessio_expires_45697a_idx",
            ),
        ),
    ]
