# Generated by Django 4.2.11 on 2026-02-27 13:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("roles", "0002_seed_roles"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="role",
            options={
                "ordering": ["level"],
                "verbose_name": "Role",
                "verbose_name_plural": "Roles",
            },
        ),
        migrations.AlterModelOptions(
            name="rolefeaturepermission",
            options={"verbose_name": "Role Feature Permission"},
        ),
        migrations.AlterField(
            model_name="role",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="role",
            name="deleted_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="role",
            name="id",
            field=models.UUIDField(
                db_index=True,
                default=uuid.uuid4,
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="role",
            name="is_global",
            field=models.BooleanField(
                default=False,
                help_text="Global roles (ROOT, SUPERADMIN) are not org-scoped.",
            ),
        ),
        migrations.AlterField(
            model_name="role",
            name="level",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (0, "ROOT"),
                    (10, "SUPERADMIN"),
                    (20, "ADMIN_PLUS"),
                    (30, "ADMIN"),
                    (40, "END_USER"),
                ],
                db_index=True,
                help_text="Lower = higher privilege. ROOT=0, END_USER=40.",
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="role",
            name="name",
            field=models.CharField(db_index=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name="rolefeaturepermission",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="rolefeaturepermission",
            name="deleted_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="rolefeaturepermission",
            name="feature",
            field=models.CharField(
                db_index=True,
                help_text="Feature flag string e.g. 'reports.export'",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="rolefeaturepermission",
            name="id",
            field=models.UUIDField(
                db_index=True,
                default=uuid.uuid4,
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
