# Generated by Django 4.2.11 on 2026-02-27 13:05

import apps.core.validators
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("roles", "0003_alter_role_options_and_more"),
        ("organizations", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="organization",
            options={"ordering": ["name"], "verbose_name": "Organization"},
        ),
        migrations.AlterModelOptions(
            name="organizationmembership",
            options={"verbose_name": "Organization Membership"},
        ),
        migrations.AlterField(
            model_name="organization",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_organizations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="organization",
            name="custom_domain",
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="organization",
            name="deleted_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="organization",
            name="deployment_mode",
            field=models.CharField(
                choices=[("saas", "SaaS"), ("self_hosted", "Self-Hosted")],
                db_index=True,
                default="saas",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="organization",
            name="id",
            field=models.UUIDField(
                db_index=True,
                default=uuid.uuid4,
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="organization",
            name="is_suspended",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name="organization",
            name="name",
            field=models.CharField(
                max_length=100,
                validators=[apps.core.validators.validate_organization_name],
            ),
        ),
        migrations.AlterField(
            model_name="organization",
            name="slug",
            field=models.SlugField(
                max_length=100,
                unique=True,
                validators=[apps.core.validators.validate_slug],
            ),
        ),
        migrations.AlterField(
            model_name="organizationmembership",
            name="added_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="added_members",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="organizationmembership",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="organizationmembership",
            name="deleted_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="organizationmembership",
            name="id",
            field=models.UUIDField(
                db_index=True,
                default=uuid.uuid4,
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="organizationmembership",
            name="role",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="memberships",
                to="roles.role",
            ),
        ),
        migrations.AddIndex(
            model_name="organization",
            index=models.Index(
                fields=["is_active", "is_deleted"],
                name="organizatio_is_acti_441a35_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="organization",
            index=models.Index(
                fields=["deployment_mode", "is_active"],
                name="organizatio_deploym_b54d38_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="organizationmembership",
            index=models.Index(
                fields=["organization", "role", "is_active"],
                name="organizatio_organiz_31ef7d_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="organizationmembership",
            index=models.Index(
                fields=["user", "is_active"], name="organizatio_user_id_c5f3a8_idx"
            ),
        ),
    ]
